#! /bin/bash
#
#$Author: ee364h10 $
#$Date: 2016-08-24 10:15:02 -0400 (Wed, 24 Aug 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F16/students/ee364h10/Lab00/testheader $
#$Revision: 91712 $


Arr=(1 2 3 "Hello") #Declare array
echo ${Arr[0]} #Print first element
echo ${Arr[*]} #Print all elements
Arr[0]=7 #Assign first element to 7
echo ${#Arr[*]} #Get size of array
echo ${!Arr[*]} #Get list of indices

Vals="hello hi hola hiya"
Arrval=($Vals)
echo ${Arrval[*]}

A[27]="x"
A[6]="y"
A[86]="z"
echo "${!A[*]}"

for I in ${A[*]}
do
    echo "$I"
done