# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomographyGUI.ui'
#
# Created: Mon Nov 28 22:49:54 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EffectList = QtGui.QComboBox(self.centralwidget)
        self.EffectList.setGeometry(QtCore.QRect(80, 460, 291, 27))
        self.EffectList.setObjectName("EffectList")
        self.EffectList.addItem("")
        self.EffectList.addItem("")
        self.EffectList.addItem("")
        self.EffectList.addItem("")
        self.EffectList.addItem("")
        self.EffectList.addItem("")
        self.EffectList.addItem("")
        self.TransformButton = QtGui.QPushButton(self.centralwidget)
        self.TransformButton.setGeometry(QtCore.QRect(70, 500, 92, 27))
        self.TransformButton.setObjectName("TransformButton")
        self.ResetButton = QtGui.QPushButton(self.centralwidget)
        self.ResetButton.setGeometry(QtCore.QRect(180, 500, 92, 27))
        self.ResetButton.setObjectName("ResetButton")
        self.SaveButton = QtGui.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(290, 500, 92, 27))
        self.SaveButton.setObjectName("SaveButton")
        self.effectLabel = QtGui.QLabel(self.centralwidget)
        self.effectLabel.setGeometry(QtCore.QRect(10, 460, 62, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.effectLabel.setFont(font)
        self.effectLabel.setObjectName("effectLabel")
        self.pointBox1 = QtGui.QLineEdit(self.centralwidget)
        self.pointBox1.setGeometry(QtCore.QRect(520, 460, 121, 31))
        self.pointBox1.setObjectName("pointBox1")
        self.pointBox4 = QtGui.QLineEdit(self.centralwidget)
        self.pointBox4.setGeometry(QtCore.QRect(660, 500, 121, 31))
        self.pointBox4.setObjectName("pointBox4")
        self.pointBox3 = QtGui.QLineEdit(self.centralwidget)
        self.pointBox3.setGeometry(QtCore.QRect(520, 500, 121, 31))
        self.pointBox3.setObjectName("pointBox3")
        self.pointBox2 = QtGui.QLineEdit(self.centralwidget)
        self.pointBox2.setGeometry(QtCore.QRect(660, 460, 121, 31))
        self.pointBox2.setObjectName("pointBox2")
        self.SourceView = QtGui.QGraphicsView(self.centralwidget)
        self.SourceView.setGeometry(QtCore.QRect(10, 70, 371, 371))
        self.SourceView.setObjectName("SourceView")
        self.TargetView = QtGui.QGraphicsView(self.centralwidget)
        self.TargetView.setGeometry(QtCore.QRect(410, 70, 371, 371))
        self.TargetView.setObjectName("TargetView")
        self.PointButton = QtGui.QPushButton(self.centralwidget)
        self.PointButton.setGeometry(QtCore.QRect(410, 460, 101, 71))
        self.PointButton.setObjectName("PointButton")
        self.SourceLoad = QtGui.QPushButton(self.centralwidget)
        self.SourceLoad.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.SourceLoad.setObjectName("SourceLoad")
        self.TargetLoad = QtGui.QPushButton(self.centralwidget)
        self.TargetLoad.setGeometry(QtCore.QRect(410, 30, 131, 31))
        self.TargetLoad.setObjectName("TargetLoad")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectList.setItemText(0, QtGui.QApplication.translate("mainWindow", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectList.setItemText(1, QtGui.QApplication.translate("mainWindow", "Rotate 90°", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectList.setItemText(2, QtGui.QApplication.translate("mainWindow", "Rotate 180°", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectList.setItemText(3, QtGui.QApplication.translate("mainWindow", "Rotate 270°", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectList.setItemText(4, QtGui.QApplication.translate("mainWindow", "Flip Horizontally", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectList.setItemText(5, QtGui.QApplication.translate("mainWindow", "Flip Vertically", None, QtGui.QApplication.UnicodeUTF8))
        self.EffectList.setItemText(6, QtGui.QApplication.translate("mainWindow", "Transpose", None, QtGui.QApplication.UnicodeUTF8))
        self.TransformButton.setText(QtGui.QApplication.translate("mainWindow", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetButton.setText(QtGui.QApplication.translate("mainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveButton.setText(QtGui.QApplication.translate("mainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.effectLabel.setText(QtGui.QApplication.translate("mainWindow", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.PointButton.setText(QtGui.QApplication.translate("mainWindow", "Acquire Points", None, QtGui.QApplication.UnicodeUTF8))
        self.SourceLoad.setText(QtGui.QApplication.translate("mainWindow", "Load Source", None, QtGui.QApplication.UnicodeUTF8))
        self.TargetLoad.setText(QtGui.QApplication.translate("mainWindow", "Load Target", None, QtGui.QApplication.UnicodeUTF8))

